-- ============================================================
-- EAP Enterprise Agent Platform  -  OceanBase DDL
-- 数据库模式：Oracle 兼容模式（com.oceanbase.jdbc.Driver）
-- 执行前请确认已切换到目标 Schema / Database
--
-- 主键策略说明：
--   IDENTITY  ：数据库自增，对应 MyBatis-Plus IdType.AUTO
--               适用于系统内部产生的业务数据（任务、子任务等）
--   NUMBER PK ：应用层雪花算法（ASSIGN_ID），主键由 MP 在 INSERT 前填充
--               适用于需要跨系统幂等/分布式的表（线索、OCR 文件等）
-- ============================================================

-- ============================================================
-- 二、疑点线索结果表
-- 对应实体：ClueResult.java  |  主键：MP 雪花算法 ASSIGN_ID
-- ============================================================

CREATE TABLE clue_result (
    id               NUMBER          NOT NULL PRIMARY KEY,     -- MP 雪花算法，避免 OceanBase RETURNING 参数位异常
    apply_code       VARCHAR2(64)    NOT NULL,                 -- 机构/申请编码
    clue_type        VARCHAR2(64),                             -- UNTENDERED / SPLIT_PURCHASE / COLLUSIVE_BID / CONFLICT_OF_INTEREST
    risk_level       VARCHAR2(16),                             -- HIGH / MEDIUM / LOW
    clue_title       VARCHAR2(512),                            -- 线索标题
    clue_detail      CLOB,                                     -- 线索详情（规则命中的具体数据描述）
    related_amount   NUMBER(18, 2),                            -- 涉及金额（元）
    related_supplier VARCHAR2(512),                            -- 涉及供应商名称
    rule_name        VARCHAR2(128),                            -- 命中的规则名称
    status           VARCHAR2(32)    DEFAULT 'PENDING',        -- PENDING / CONFIRMED / DISMISSED
    created_at       TIMESTAMP
);

COMMENT ON TABLE  clue_result IS '疑点线索结果表，由规则引擎写入，Agent 读取后进行智能分析';
COMMENT ON COLUMN clue_result.apply_code  IS '机构/申请编码，用于隔离不同机构的线索数据';
COMMENT ON COLUMN clue_result.clue_type   IS '线索类型：UNTENDERED/SPLIT_PURCHASE/COLLUSIVE_BID/CONFLICT_OF_INTEREST';
COMMENT ON COLUMN clue_result.status      IS '处理状态：PENDING=待处理，CONFIRMED=已确认，DISMISSED=已驳回';


-- ============================================================
-- 三、Agent 主任务表
-- 对应实体：AgentTask.java  |  主键：数据库自增 IDENTITY（IdType.AUTO）
-- ============================================================

CREATE TABLE agent_task (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name       VARCHAR2(256),                             -- 任务名称
    goal            CLOB,                                      -- 任务目标描述（用户输入的原始诉求）
    status          VARCHAR2(32),                              -- PENDING/RUNNING/REVIEWING/COMMUNICATING/COMPLETED/FAILED
    planner_result  CLOB,                                      -- Planner 输出的执行计划（JSON）
    executor_result CLOB,                                      -- Executor 执行结果汇总
    reviewer_score  NUMBER(3),                                 -- Reviewer 评分（0~100，低于阈值触发重试）
    final_report    CLOB,                                      -- Communicator 生成的最终报告
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP
);

COMMENT ON TABLE  agent_task IS 'Agent 主任务表，记录完整任务生命周期';
COMMENT ON COLUMN agent_task.status         IS '任务状态：PENDING/RUNNING/REVIEWING/COMMUNICATING/COMPLETED/FAILED';
COMMENT ON COLUMN agent_task.planner_result IS 'Planner 输出的子任务计划，JSON 数组格式';
COMMENT ON COLUMN agent_task.reviewer_score IS 'Reviewer 评审评分 0~100，低于配置阈值触发重试';


-- ============================================================
-- 四、Agent 子任务表
-- 对应实体：AgentSubTask.java  |  主键：数据库自增 IDENTITY（IdType.AUTO）
-- ============================================================

CREATE TABLE agent_sub_task (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     NUMBER          NOT NULL,                      -- 关联 agent_task.id
    sequence    NUMBER(5),                                     -- 执行顺序（从 1 开始，Planner 规划时确定）
    description CLOB,                                          -- 子任务描述（Planner 输出的步骤说明）
    tool_name   VARCHAR2(128),                                 -- 调用的工具名称，对应 EnterpriseTool 实现类
    tool_params CLOB,                                          -- 工具调用参数（JSON），由 Executor 填充
    result      CLOB,                                          -- 工具执行结果
    status      VARCHAR2(32),                                  -- PENDING / RUNNING / COMPLETED / FAILED
    created_at  TIMESTAMP
);

COMMENT ON TABLE  agent_sub_task IS 'Agent 子任务表，Executor 按 Planner 计划逐步执行';
COMMENT ON COLUMN agent_sub_task.task_id     IS '所属主任务 ID，关联 agent_task.id';
COMMENT ON COLUMN agent_sub_task.sequence    IS '执行顺序，从 1 开始';
COMMENT ON COLUMN agent_sub_task.tool_name   IS '调用的工具名称，对应 EnterpriseTool 实现类';
COMMENT ON COLUMN agent_sub_task.tool_params IS '工具入参 JSON，由 Executor 根据 Planner 计划填充';


-- ============================================================
-- 五、OCR / 多模态识别文件入库
-- 对应实体：OcrFileMain.java / OcrFileSplit.java
-- 主键：MP 雪花算法 ASSIGN_ID
--
-- 单图/无拆分路径：createMain → markMainProcessing
--                 → saveDirectResult（同时写 split 表 1 条 split_index=0）→ SUCCESS
-- 多页/拆分路径：  createMain → saveSplits（批量建分片）
--                 → 逐片 saveSplitResult → 全片 SUCCESS 后自动聚合主表 → SUCCESS
-- ============================================================

-- OCR 主文件表
CREATE TABLE ocr_file_main (
    id            NUMBER          NOT NULL PRIMARY KEY,        -- MP 雪花算法，避免 OceanBase RETURNING 参数位异常
    business_no   VARCHAR2(64)    NOT NULL,                    -- 业务流水号（同一请求唯一标识，可作幂等键）
    source        VARCHAR2(32)    NOT NULL,                    -- 识别来源：DAZHI_OCR / ZHENGYAN_MULTIMODAL
    file_name     VARCHAR2(255)   NOT NULL,                    -- 原始文件名
    file_type     VARCHAR2(32),                                -- 文件类型：pdf / jpg / png / tiff 等
    file_size     NUMBER(18),                                  -- 文件大小（字节）
    file_path     VARCHAR2(512),                               -- 文件完整存储路径（含 bucket，如 bucket/path/to/file.pdf）
    batch_no      VARCHAR2(64),                                -- 批次流水号，关联 ocr_pipeline_batch.batch_no
    ocr_status    VARCHAR2(32)    DEFAULT 'PENDING',           -- PENDING / PROCESSING / SUCCESS / FAILED
    analysis_status VARCHAR2(32)  DEFAULT 'PENDING',           -- PENDING / PROCESSING / SUCCESS / FAILED / SKIPPED
    total_pages   NUMBER(10)      DEFAULT 0,                   -- 分片数（0=未拆分整文件；单图路径写入 1）
    prompt        CLOB,                                        -- 发给识别引擎的提示词（便于问题排查和效果回溯）
    ocr_result    CLOB,                                        -- 汇总识别文本（无拆分时直写；有拆分时聚合各片）
    error_message VARCHAR2(1024),                              -- 识别失败原因
    app_code      VARCHAR2(64),                                -- 大智部 appCode / 正言 appId
    extra_info    CLOB,                                        -- 扩展 JSON（证件类型、客户编码等自定义字段）
    created_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ocr_file_main_biz_no UNIQUE (business_no)
);

COMMENT ON TABLE  ocr_file_main IS 'OCR/多模态识别主文件记录表';
COMMENT ON COLUMN ocr_file_main.id           IS 'MP 雪花算法主键，应用层生成后随 INSERT 写入';
COMMENT ON COLUMN ocr_file_main.business_no  IS '业务流水号，全局唯一，可作为幂等键防重';
COMMENT ON COLUMN ocr_file_main.source       IS '识别来源：DAZHI_OCR=大智部OCR，ZHENGYAN_MULTIMODAL=正言多模态';
COMMENT ON COLUMN ocr_file_main.file_path    IS '文件完整存储路径，格式：bucket/path/to/file，不含协议前缀';
COMMENT ON COLUMN ocr_file_main.batch_no        IS '所属批次流水号，关联 ocr_pipeline_batch.batch_no；单文件时可为 NULL';
COMMENT ON COLUMN ocr_file_main.ocr_status      IS '识别状态：PENDING/PROCESSING/SUCCESS/FAILED';
COMMENT ON COLUMN ocr_file_main.analysis_status IS '多模态语义分析状态：PENDING/PROCESSING/SUCCESS/FAILED/SKIPPED';
COMMENT ON COLUMN ocr_file_main.total_pages  IS '分片总数：0=未拆分整文件，单图路径写入 1，多页拆分时写入实际页数';
COMMENT ON COLUMN ocr_file_main.prompt       IS '识别时使用的提示词，入库用于问题排查和效果回溯';
COMMENT ON COLUMN ocr_file_main.ocr_result   IS '最终识别文本：无拆分时直接写入，有拆分时按 split_index 顺序聚合';
COMMENT ON COLUMN ocr_file_main.extra_info   IS '扩展 JSON，存放来源系统的自定义业务字段';

-- OCR 分片文件表
CREATE TABLE ocr_file_split (
    id            NUMBER          NOT NULL PRIMARY KEY,        -- MP 雪花算法
    main_id       NUMBER          NOT NULL,                    -- 关联 ocr_file_main.id
    split_index   NUMBER(10)      NOT NULL,                    -- 分片序号（从 0 开始；单图路径固定为 0）
    page_no       NUMBER(10),                                  -- 原始文档页码（PDF 从 1 开始；单图为 1）
    file_path     VARCHAR2(512),                               -- 分片文件完整存储路径（含 bucket，如 bucket/path/to/page_1.jpg）
    file_type     VARCHAR2(32),                                -- 分片文件类型（jpg / png / tiff 等）
    file_size     NUMBER(18),                                  -- 分片大小（字节）
    ocr_status    VARCHAR2(32)    DEFAULT 'PENDING',           -- PENDING / PROCESSING / SUCCESS / FAILED
    prompt        CLOB,                                        -- 该分片使用的提示词（可与主文件相同或按页定制）
    image_base64 CLOB,                                        -- 该分片使用的原始图片 base64（用于追溯/重跑；可能较大）
    ocr_result    CLOB,                                        -- 该分片 OCR 识别文本（大智部等）
    llm_result    CLOB,                                        -- 该分片大模型/多模态识别正文（与 ocr_result 分列）
    error_message VARCHAR2(1024),                              -- 该分片失败原因
    created_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ocr_split_main FOREIGN KEY (main_id) REFERENCES ocr_file_main(id)
);

COMMENT ON TABLE  ocr_file_split IS 'OCR/多模态识别分片文件记录表';
COMMENT ON COLUMN ocr_file_split.main_id     IS '所属主文件 ID，关联 ocr_file_main.id';
COMMENT ON COLUMN ocr_file_split.split_index IS '分片序号，从 0 开始，用于按序拼接汇总文本；单图路径固定为 0';
COMMENT ON COLUMN ocr_file_split.page_no     IS '原始文档页码，多页 PDF 时每页一条；单图路径固定为 1';
COMMENT ON COLUMN ocr_file_split.file_path   IS '分片文件完整存储路径，格式：bucket/path/to/file，不含协议前缀';
COMMENT ON COLUMN ocr_file_split.prompt      IS '该分片使用的提示词，可与主文件保持一致或按页定制';
COMMENT ON COLUMN ocr_file_split.ocr_result  IS '该分片 OCR 识别文本（大智部等）';
COMMENT ON COLUMN ocr_file_split.llm_result   IS '该分片大模型/多模态识别正文（正言 img2text，与 ocr_result 分列）';


-- ============================================================
-- 五-A、OCR 流水线批次表
-- ============================================================
-- 记录一次"多文件上传"的整体进度；一个 batch_no 对应 N 条 ocr_file_main。
-- 流水线阶段：PENDING → OCR_PROCESSING → OCR_DONE → ANALYZING → ANALYZED → COMPARING → DONE
--             任意阶段失败均可变为 FAILED；部分失败走 PARTIAL_FAIL 继续下一阶段。
CREATE TABLE ocr_pipeline_batch (
    id               NUMBER          NOT NULL PRIMARY KEY,   -- MP 雪花算法
    batch_no         VARCHAR2(64)    NOT NULL,               -- 批次流水号，全局唯一
    app_code         VARCHAR2(64),                           -- 应用/租户编码
    trigger_source   VARCHAR2(32)    DEFAULT 'API',          -- API / SCHEDULER
    total_files      NUMBER(10)      DEFAULT 0,              -- 批次文件总数
    ocr_done_files   NUMBER(10)      DEFAULT 0,              -- OCR 完成文件数
    analysis_done_files NUMBER(10)   DEFAULT 0,              -- 分析完成文件数
    status           VARCHAR2(32)    DEFAULT 'PENDING',      -- PENDING/OCR_PROCESSING/OCR_DONE/ANALYZING/ANALYZED/COMPARING/DONE/PARTIAL_FAIL/FAILED
    error_message    VARCHAR2(1024),                         -- 最近一次失败原因
    extra_info       CLOB,                                   -- 扩展 JSON（调用方透传字段）
    created_at       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ocr_pipeline_batch_no UNIQUE (batch_no)
);

COMMENT ON TABLE  ocr_pipeline_batch IS 'OCR 流水线批次表，追踪多文件上传的整体处理进度';
COMMENT ON COLUMN ocr_pipeline_batch.batch_no       IS '批次流水号，一次多文件上传共用同一 batch_no';
COMMENT ON COLUMN ocr_pipeline_batch.trigger_source IS '触发来源：API=接口调用，SCHEDULER=定时任务补跑';
COMMENT ON COLUMN ocr_pipeline_batch.status         IS '批次状态机：PENDING→OCR_PROCESSING→OCR_DONE→ANALYZING→ANALYZED→COMPARING→DONE，PARTIAL_FAIL=部分失败仍继续，FAILED=严重失败';

-- ============================================================
-- 五-B、多模态语义分析结果表（正言大模型）
-- ============================================================
-- 对 ocr_file_main 中每个文件，调用正言多模态对分片图片进行结构化内容提取，
-- 如：是否加盖印章、营业执照信息、报价单金额、文档类型等。
CREATE TABLE ocr_file_analysis (
    id               NUMBER          NOT NULL PRIMARY KEY,   -- MP 雪花算法
    main_id          NUMBER          NOT NULL,               -- 关联 ocr_file_main.id
    batch_no         VARCHAR2(64),                           -- 所属批次（冗余，便于按批次查询）
    -- 结构化提取字段
    doc_type         VARCHAR2(64),                           -- 文档类型：BUSINESS_LICENSE/QUOTATION/CONTRACT/INVOICE/SEAL_PAGE/OTHER
    has_stamp        NUMBER(1)       DEFAULT 0,              -- 是否有公章（0=无，1=有）
    stamp_text       VARCHAR2(1024),                         -- 公章文字内容
    company_name     VARCHAR2(512),                          -- 公司/单位名称
    license_no       VARCHAR2(128),                          -- 营业执照统一社会信用代码
    total_amount     NUMBER(18, 2),                          -- 报价/合同总金额（元）
    key_dates        VARCHAR2(512),                          -- 关键日期（逗号分隔，如开标日期、合同日期）
    doc_summary      CLOB,                                   -- 文档摘要（100字以内，由大模型生成）
    structured_extra CLOB,                                   -- 证件/身份证等扩展字段 JSON（模型返回中未映射到上列的键）
    -- 分析元数据
    analysis_prompt  CLOB,                                   -- 分析时使用的提示词
    analysis_raw     CLOB,                                   -- 正言大模型原始响应 JSON
    status           VARCHAR2(32)    DEFAULT 'PENDING',      -- PENDING / PROCESSING / SUCCESS / FAILED / SKIPPED
    error_message    VARCHAR2(1024),
    created_at       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ocr_analysis_main FOREIGN KEY (main_id) REFERENCES ocr_file_main(id)
);

COMMENT ON TABLE  ocr_file_analysis IS '多模态语义分析结果表，存储正言大模型对文件图片的结构化提取结果';
COMMENT ON COLUMN ocr_file_analysis.main_id      IS '所属主文件 ID，关联 ocr_file_main.id';
COMMENT ON COLUMN ocr_file_analysis.doc_type     IS '文档类型：BUSINESS_LICENSE=营业执照，QUOTATION=报价单，CONTRACT=合同，INVOICE=发票，SEAL_PAGE=印章页，OTHER=其他';
COMMENT ON COLUMN ocr_file_analysis.has_stamp    IS '是否有公章：0=无，1=有';
COMMENT ON COLUMN ocr_file_analysis.license_no   IS '营业执照统一社会信用代码（18位）';
COMMENT ON COLUMN ocr_file_analysis.total_amount IS '报价单/合同总金额（元），无则 NULL';
COMMENT ON COLUMN ocr_file_analysis.analysis_raw IS '正言多模态大模型原始响应 JSON，用于问题排查';
COMMENT ON COLUMN ocr_file_analysis.structured_extra IS '扩展结构化字段 JSON：资质类别、证书编号、身份证姓名号码等';
COMMENT ON COLUMN ocr_file_analysis.status       IS '分析状态：PENDING/PROCESSING/SUCCESS/FAILED/SKIPPED（文件无图片内容时跳过）';

-- ============================================================
-- 五-C、文件相似度对比结果表
-- ============================================================
-- 存储多附件对比结果：文字相似度（分段OCR识别结果）+ 文件整体相似度（SHA-256/感知哈希）
CREATE TABLE file_similarity_result (
    id                  NUMBER          NOT NULL PRIMARY KEY,      -- MP 雪花算法主键
    business_no         VARCHAR2(128)   NOT NULL,                  -- 业务流水号（同一批对比唯一标识）
    file_a_main_id      NUMBER,                                    -- 关联 ocr_file_main.id（文件A）
    file_b_main_id      NUMBER,                                    -- 关联 ocr_file_main.id（文件B）
    file_a_name         VARCHAR2(255)   NOT NULL,                  -- 文件A名称
    file_b_name         VARCHAR2(255)   NOT NULL,                  -- 文件B名称
    file_a_sha256       VARCHAR2(64),                              -- 文件A SHA-256 摘要
    file_b_sha256       VARCHAR2(64),                              -- 文件B SHA-256 摘要
    -- 文字相似度（分段OCR结果对比，来自 ocr_file_split.ocr_result）
    text_tfidf_cosine   NUMBER(8,4),                               -- TF-IDF 余弦相似度（0~1）
    text_difflib_ratio  NUMBER(8,4),                               -- difflib SequenceMatcher ratio（0~1）
    text_longest_common NUMBER(10),                                -- 最长公共连续块字符数
    text_segments_50    NUMBER(10),                                -- 匹配片段数（≥50字符）
    text_blocks_500     NUMBER(10),                                -- 长公共块数（≥500字符）
    text_len_a          NUMBER(10),                                -- 文件A有效文字长度
    text_len_b          NUMBER(10),                                -- 文件B有效文字长度
    -- 文件整体相似度（整文件直接对比）
    file_exact_match    NUMBER(1)       DEFAULT 0,                 -- 是否完全相同（SHA-256精确匹配）
    file_visual_sim     NUMBER(8,4),                               -- 视觉感知哈希平均相似度（0~1，无则 NULL）
    -- 汇总风险
    risk_level          VARCHAR2(16),                              -- high / medium / low / unknown
    risk_label          VARCHAR2(64),                              -- 风险描述文字
    -- 元数据
    app_code            VARCHAR2(64),                              -- 应用/来源标识
    extra_detail        CLOB,                                      -- 扩展 JSON（完整 Python 响应 comparisons 字段）
    created_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fsim_main_a FOREIGN KEY (file_a_main_id) REFERENCES ocr_file_main(id),
    CONSTRAINT fk_fsim_main_b FOREIGN KEY (file_b_main_id) REFERENCES ocr_file_main(id)
);

COMMENT ON TABLE  file_similarity_result IS '文件相似度对比结果表：存储多附件对比的文字相似度（分段OCR）和文件整体相似度';
COMMENT ON COLUMN file_similarity_result.business_no        IS '同一批对比的唯一业务流水号';
COMMENT ON COLUMN file_similarity_result.text_tfidf_cosine  IS '文字相似度：TF-IDF字符级4-gram余弦，来自 ocr_file_split.ocr_result 拼接文本';
COMMENT ON COLUMN file_similarity_result.file_exact_match   IS '文件整体相似度：1=SHA-256完全相同，0=不同';
COMMENT ON COLUMN file_similarity_result.file_visual_sim    IS '文件整体相似度：PDF分页/图片感知哈希(dHash)平均值，NULL表示不支持';
COMMENT ON COLUMN file_similarity_result.extra_detail       IS '完整对比明细JSON，含公共块列表、分页哈希明细等';

-- ============================================================
-- 六、索引
-- ============================================================
-- 线索结果
CREATE INDEX idx_clue_result_apply_status ON clue_result(apply_code, status);
CREATE INDEX idx_clue_result_type         ON clue_result(clue_type, risk_level);

-- Agent 任务
CREATE INDEX idx_agent_task_status        ON agent_task(status, created_at);
CREATE INDEX idx_agent_sub_task_task      ON agent_sub_task(task_id, sequence);

-- 文件相似度结果
CREATE INDEX idx_file_sim_business_no     ON file_similarity_result(business_no);
CREATE INDEX idx_file_sim_file_a          ON file_similarity_result(file_a_main_id);
CREATE INDEX idx_file_sim_file_b          ON file_similarity_result(file_b_main_id);
CREATE INDEX idx_file_sim_risk            ON file_similarity_result(risk_level, created_at);

-- OCR 文件
CREATE INDEX idx_ocr_file_main_status     ON ocr_file_main(ocr_status, created_at);
CREATE INDEX idx_ocr_file_main_source     ON ocr_file_main(source, ocr_status);
CREATE INDEX idx_ocr_file_main_batch      ON ocr_file_main(batch_no, ocr_status);
CREATE INDEX idx_ocr_file_main_analysis   ON ocr_file_main(batch_no, analysis_status);
CREATE INDEX idx_ocr_file_split_main      ON ocr_file_split(main_id, split_index);
CREATE INDEX idx_ocr_file_split_status    ON ocr_file_split(ocr_status);

-- 流水线批次
CREATE INDEX idx_pipeline_batch_status    ON ocr_pipeline_batch(status, updated_at);
CREATE INDEX idx_pipeline_batch_app       ON ocr_pipeline_batch(app_code, status);

-- 多模态分析
CREATE INDEX idx_ocr_analysis_main        ON ocr_file_analysis(main_id);
CREATE INDEX idx_ocr_analysis_batch       ON ocr_file_analysis(batch_no, status);
CREATE INDEX idx_ocr_analysis_doc_type    ON ocr_file_analysis(doc_type, has_stamp);

-- ============================================================
-- 变更脚本 V2：为存量表补加流水线相关字段（首次部署时已包含，仅升级时执行）
-- ============================================================

-- ocr_file_main 补加 batch_no 和 analysis_status 列
ALTER TABLE ocr_file_main ADD batch_no         VARCHAR2(64);
ALTER TABLE ocr_file_main ADD analysis_status  VARCHAR2(32) DEFAULT 'PENDING';

COMMENT ON COLUMN ocr_file_main.batch_no        IS '所属批次流水号，关联 ocr_pipeline_batch.batch_no；单文件时可为 NULL';
COMMENT ON COLUMN ocr_file_main.analysis_status IS '多模态语义分析状态：PENDING/PROCESSING/SUCCESS/FAILED/SKIPPED';

-- 为新列补建索引（若在 CREATE TABLE 阶段已执行则跳过）
-- CREATE INDEX idx_ocr_file_main_batch    ON ocr_file_main(batch_no, ocr_status);
-- CREATE INDEX idx_ocr_file_main_analysis ON ocr_file_main(batch_no, analysis_status);
