-- ============================================================
-- EAP Enterprise Agent Platform  -  OceanBase DDL
-- 数据库模式：Oracle 兼容模式（com.oceanbase.jdbc.Driver）
-- 执行前请确认已切换到目标 Schema / Database
--
-- 主键策略说明：
--   IDENTITY  ：数据库自增，对应 MyBatis-Plus IdType.AUTO
--               适用于系统内部产生的业务数据（任务、子任务等）
--   NUMBER PK ：应用层雪花算法（ASSIGN_ID），主键由 MP 在 INSERT 前填充
--               适用于需要跨系统幂等/分布式的表（线索、OCR 文件等）
-- ============================================================

-- ============================================================
-- 二、疑点线索结果表
-- 对应实体：ClueResult.java  |  主键：MP 雪花算法 ASSIGN_ID
-- ============================================================

CREATE TABLE clue_result (
    id               NUMBER          NOT NULL PRIMARY KEY,     -- MP 雪花算法，避免 OceanBase RETURNING 参数位异常
    apply_code       VARCHAR2(64)    NOT NULL,                 -- 机构/申请编码
    clue_type        VARCHAR2(64),                             -- UNTENDERED / SPLIT_PURCHASE / COLLUSIVE_BID / CONFLICT_OF_INTEREST
    risk_level       VARCHAR2(16),                             -- HIGH / MEDIUM / LOW
    clue_title       VARCHAR2(512),                            -- 线索标题
    clue_detail      CLOB,                                     -- 线索详情（规则命中的具体数据描述）
    related_amount   NUMBER(18, 2),                            -- 涉及金额（元）
    related_supplier VARCHAR2(512),                            -- 涉及供应商名称
    rule_name        VARCHAR2(128),                            -- 命中的规则名称
    status           VARCHAR2(32)    DEFAULT 'PENDING',        -- PENDING / CONFIRMED / DISMISSED
    created_at       TIMESTAMP
);

COMMENT ON TABLE  clue_result IS '疑点线索结果表，由规则引擎写入，Agent 读取后进行智能分析';
COMMENT ON COLUMN clue_result.apply_code  IS '机构/申请编码，用于隔离不同机构的线索数据';
COMMENT ON COLUMN clue_result.clue_type   IS '线索类型：UNTENDERED/SPLIT_PURCHASE/COLLUSIVE_BID/CONFLICT_OF_INTEREST';
COMMENT ON COLUMN clue_result.status      IS '处理状态：PENDING=待处理，CONFIRMED=已确认，DISMISSED=已驳回';


-- ============================================================
-- 三、Agent 主任务表
-- 对应实体：AgentTask.java  |  主键：数据库自增 IDENTITY（IdType.AUTO）
-- ============================================================

CREATE TABLE agent_task (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name       VARCHAR2(256),                             -- 任务名称
    goal            CLOB,                                      -- 任务目标描述（用户输入的原始诉求）
    status          VARCHAR2(32),                              -- PENDING/RUNNING/REVIEWING/COMMUNICATING/COMPLETED/FAILED
    planner_result  CLOB,                                      -- Planner 输出的执行计划（JSON）
    executor_result CLOB,                                      -- Executor 执行结果汇总
    reviewer_score  NUMBER(3),                                 -- Reviewer 评分（0~100，低于阈值触发重试）
    final_report    CLOB,                                      -- Communicator 生成的最终报告
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP
);

COMMENT ON TABLE  agent_task IS 'Agent 主任务表，记录完整任务生命周期';
COMMENT ON COLUMN agent_task.status         IS '任务状态：PENDING/RUNNING/REVIEWING/COMMUNICATING/COMPLETED/FAILED';
COMMENT ON COLUMN agent_task.planner_result IS 'Planner 输出的子任务计划，JSON 数组格式';
COMMENT ON COLUMN agent_task.reviewer_score IS 'Reviewer 评审评分 0~100，低于配置阈值触发重试';


-- ============================================================
-- 四、Agent 子任务表
-- 对应实体：AgentSubTask.java  |  主键：数据库自增 IDENTITY（IdType.AUTO）
-- ============================================================

CREATE TABLE agent_sub_task (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     NUMBER          NOT NULL,                      -- 关联 agent_task.id
    sequence    NUMBER(5),                                     -- 执行顺序（从 1 开始，Planner 规划时确定）
    description CLOB,                                          -- 子任务描述（Planner 输出的步骤说明）
    tool_name   VARCHAR2(128),                                 -- 调用的工具名称，对应 EnterpriseTool 实现类
    tool_params CLOB,                                          -- 工具调用参数（JSON），由 Executor 填充
    result      CLOB,                                          -- 工具执行结果
    status      VARCHAR2(32),                                  -- PENDING / RUNNING / COMPLETED / FAILED
    created_at  TIMESTAMP
);

COMMENT ON TABLE  agent_sub_task IS 'Agent 子任务表，Executor 按 Planner 计划逐步执行';
COMMENT ON COLUMN agent_sub_task.task_id     IS '所属主任务 ID，关联 agent_task.id';
COMMENT ON COLUMN agent_sub_task.sequence    IS '执行顺序，从 1 开始';
COMMENT ON COLUMN agent_sub_task.tool_name   IS '调用的工具名称，对应 EnterpriseTool 实现类';
COMMENT ON COLUMN agent_sub_task.tool_params IS '工具入参 JSON，由 Executor 根据 Planner 计划填充';


-- ============================================================
-- 五、OCR / 多模态识别文件入库
-- 对应实体：OcrFileMain.java / OcrFileSplit.java
-- 主键：MP 雪花算法 ASSIGN_ID
--
-- 单图/无拆分路径：createMain → markMainProcessing
--                 → saveDirectResult（同时写 split 表 1 条 split_index=0）→ SUCCESS
-- 多页/拆分路径：  createMain → saveSplits（批量建分片）
--                 → 逐片 saveSplitResult → 全片 SUCCESS 后自动聚合主表 → SUCCESS
-- ============================================================

-- OCR 主文件表
CREATE TABLE ocr_file_main (
    id            NUMBER          NOT NULL PRIMARY KEY,        -- MP 雪花算法，避免 OceanBase RETURNING 参数位异常
    business_no   VARCHAR2(64)    NOT NULL,                    -- 业务流水号（同一请求唯一标识，可作幂等键）
    source        VARCHAR2(32)    NOT NULL,                    -- 识别来源：DAZHI_OCR / ZHENGYAN_MULTIMODAL
    file_name     VARCHAR2(255)   NOT NULL,                    -- 原始文件名
    file_type     VARCHAR2(32),                                -- 文件类型：pdf / jpg / png / tiff 等
    file_size     NUMBER(18),                                  -- 文件大小（字节）
    file_path     VARCHAR2(512),                               -- 文件完整存储路径（含 bucket，如 bucket/path/to/file.pdf）
    ocr_status    VARCHAR2(32)    DEFAULT 'PENDING',           -- PENDING / PROCESSING / SUCCESS / FAILED
    total_pages   NUMBER(10)      DEFAULT 0,                   -- 分片数（0=未拆分整文件；单图路径写入 1）
    prompt        CLOB,                                        -- 发给识别引擎的提示词（便于问题排查和效果回溯）
    ocr_result    CLOB,                                        -- 汇总识别文本（无拆分时直写；有拆分时聚合各片）
    error_message VARCHAR2(1024),                              -- 识别失败原因
    app_code      VARCHAR2(64),                                -- 大智部 appCode / 正言 appId
    extra_info    CLOB,                                        -- 扩展 JSON（证件类型、客户编码等自定义字段）
    created_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ocr_file_main_biz_no UNIQUE (business_no)
);

COMMENT ON TABLE  ocr_file_main IS 'OCR/多模态识别主文件记录表';
COMMENT ON COLUMN ocr_file_main.id           IS 'MP 雪花算法主键，应用层生成后随 INSERT 写入';
COMMENT ON COLUMN ocr_file_main.business_no  IS '业务流水号，全局唯一，可作为幂等键防重';
COMMENT ON COLUMN ocr_file_main.source       IS '识别来源：DAZHI_OCR=大智部OCR，ZHENGYAN_MULTIMODAL=正言多模态';
COMMENT ON COLUMN ocr_file_main.file_path    IS '文件完整存储路径，格式：bucket/path/to/file，不含协议前缀';
COMMENT ON COLUMN ocr_file_main.ocr_status   IS '识别状态：PENDING/PROCESSING/SUCCESS/FAILED';
COMMENT ON COLUMN ocr_file_main.total_pages  IS '分片总数：0=未拆分整文件，单图路径写入 1，多页拆分时写入实际页数';
COMMENT ON COLUMN ocr_file_main.prompt       IS '识别时使用的提示词，入库用于问题排查和效果回溯';
COMMENT ON COLUMN ocr_file_main.ocr_result   IS '最终识别文本：无拆分时直接写入，有拆分时按 split_index 顺序聚合';
COMMENT ON COLUMN ocr_file_main.extra_info   IS '扩展 JSON，存放来源系统的自定义业务字段';

-- OCR 分片文件表
CREATE TABLE ocr_file_split (
    id            NUMBER          NOT NULL PRIMARY KEY,        -- MP 雪花算法
    main_id       NUMBER          NOT NULL,                    -- 关联 ocr_file_main.id
    split_index   NUMBER(10)      NOT NULL,                    -- 分片序号（从 0 开始；单图路径固定为 0）
    page_no       NUMBER(10),                                  -- 原始文档页码（PDF 从 1 开始；单图为 1）
    file_path     VARCHAR2(512),                               -- 分片文件完整存储路径（含 bucket，如 bucket/path/to/page_1.jpg）
    file_type     VARCHAR2(32),                                -- 分片文件类型（jpg / png / tiff 等）
    file_size     NUMBER(18),                                  -- 分片大小（字节）
    ocr_status    VARCHAR2(32)    DEFAULT 'PENDING',           -- PENDING / PROCESSING / SUCCESS / FAILED
    prompt        CLOB,                                        -- 该分片使用的提示词（可与主文件相同或按页定制）
    image_base64 CLOB,                                        -- 该分片使用的原始图片 base64（用于追溯/重跑；可能较大）
    ocr_result    CLOB,                                        -- 该分片识别文本
    error_message VARCHAR2(1024),                              -- 该分片失败原因
    created_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ocr_split_main FOREIGN KEY (main_id) REFERENCES ocr_file_main(id)
);

COMMENT ON TABLE  ocr_file_split IS 'OCR/多模态识别分片文件记录表';
COMMENT ON COLUMN ocr_file_split.main_id     IS '所属主文件 ID，关联 ocr_file_main.id';
COMMENT ON COLUMN ocr_file_split.split_index IS '分片序号，从 0 开始，用于按序拼接汇总文本；单图路径固定为 0';
COMMENT ON COLUMN ocr_file_split.page_no     IS '原始文档页码，多页 PDF 时每页一条；单图路径固定为 1';
COMMENT ON COLUMN ocr_file_split.file_path   IS '分片文件完整存储路径，格式：bucket/path/to/file，不含协议前缀';
COMMENT ON COLUMN ocr_file_split.prompt      IS '该分片使用的提示词，可与主文件保持一致或按页定制';


-- ============================================================
-- 六、索引
-- ============================================================
-- 线索结果
CREATE INDEX idx_clue_result_apply_status ON clue_result(apply_code, status);
CREATE INDEX idx_clue_result_type         ON clue_result(clue_type, risk_level);

-- Agent 任务
CREATE INDEX idx_agent_task_status        ON agent_task(status, created_at);
CREATE INDEX idx_agent_sub_task_task      ON agent_sub_task(task_id, sequence);

-- OCR 文件
CREATE INDEX idx_ocr_file_main_status     ON ocr_file_main(ocr_status, created_at);
CREATE INDEX idx_ocr_file_main_source     ON ocr_file_main(source, ocr_status);
CREATE INDEX idx_ocr_file_split_main      ON ocr_file_split(main_id, split_index);
CREATE INDEX idx_ocr_file_split_status    ON ocr_file_split(ocr_status);
