-- ============================================================
-- EAP Enterprise Agent Platform - OceanBase DDL
-- 模式：Oracle 兼容模式（com.oceanbase.jdbc.Driver）
-- 执行前请确认已切换到目标 Schema/Database
-- ============================================================

-- 招标项目表
CREATE TABLE IF NOT EXISTS procurement_project (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code     VARCHAR2(64)   NOT NULL,
    project_name     VARCHAR2(256)  NOT NULL,
    org_code         VARCHAR2(64)   NOT NULL,
    contract_amount  NUMBER(18, 2),
    bid_method       VARCHAR2(64),
    supplier_name    VARCHAR2(256),
    supplier_id      VARCHAR2(64),
    project_date     DATE,
    has_bid_process  NUMBER(1)  DEFAULT 0,
    synced_at        TIMESTAMP
);

-- 投标记录表（围标串标规则核心数据表）
CREATE TABLE IF NOT EXISTS procurement_bid (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bid_project_id          VARCHAR2(64)   NOT NULL,
    project_name            VARCHAR2(256),
    supplier_name           VARCHAR2(256),
    supplier_id             VARCHAR2(64),
    bid_amount              NUMBER(18, 2),
    bid_content             CLOB,
    legal_person            VARCHAR2(128),
    shareholders            CLOB,
    is_winner               NUMBER(1)  DEFAULT 0,
    bid_date                DATE,
    bid_document_url        VARCHAR2(512),
    bid_document_minio_pth  VARCHAR2(512),
    bid_document_text       CLOB,        -- 投标文件全文（供文本相似度分析）
    bid_price_detail        CLOB,
    created_at              TIMESTAMP
);

-- 供应商工商信息表（围标串标/利益冲突规则交叉比对）
CREATE TABLE IF NOT EXISTS supplier_info (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id         VARCHAR2(64)   NOT NULL,
    supplier_name       VARCHAR2(256)  NOT NULL,
    legal_person        VARCHAR2(128),  -- 法定代表人（围标检测关键字段）
    registered_capital  NUMBER(18, 2),
    shareholders        CLOB,           -- JSON格式: [{"name":"xx","ratio":30}]
    business_scope      CLOB,
    risk_level          VARCHAR2(16),   -- LOW / MEDIUM / HIGH
    synced_at           TIMESTAMP
);

-- 付款台账表（大额未招标/化整为零规则）
CREATE TABLE IF NOT EXISTS payment_record (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_code         VARCHAR2(64)   NOT NULL,
    contract_no      VARCHAR2(64),
    supplier_name    VARCHAR2(256),
    supplier_id      VARCHAR2(64),
    payment_amount   NUMBER(18, 2),
    payment_date     DATE,
    project_category VARCHAR2(128),
    payment_purpose  CLOB,
    created_at       TIMESTAMP
);

-- 内部员工表（利益冲突规则）
CREATE TABLE IF NOT EXISTS internal_employee (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_code      VARCHAR2(64)   NOT NULL,
    employee_name VARCHAR2(128)  NOT NULL,
    department    VARCHAR2(256),
    position      VARCHAR2(128),
    synced_at     TIMESTAMP
);

-- 采购合同表
CREATE TABLE IF NOT EXISTS procurement_contract (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_no     VARCHAR2(64)   NOT NULL,
    project_code    VARCHAR2(64),
    supplier_id     VARCHAR2(64),
    supplier_name   VARCHAR2(256),
    contract_amount NUMBER(18, 2),
    sign_date       DATE,
    org_code        VARCHAR2(64),
    created_at      TIMESTAMP
);

-- 疑点线索结果表（规则引擎写入，Agent 读取分析）
CREATE TABLE IF NOT EXISTS clue_result (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apply_code         VARCHAR2(64)   NOT NULL,
    clue_type        VARCHAR2(64),   -- UNTENDERED / SPLIT_PURCHASE / COLLUSIVE_BID / CONFLICT_OF_INTEREST
    risk_level       VARCHAR2(16),   -- HIGH / MEDIUM / LOW
    clue_title       VARCHAR2(512),
    clue_detail      CLOB,
    related_amount   NUMBER(18, 2),
    related_supplier VARCHAR2(512),
    rule_name        VARCHAR2(128),
    status           VARCHAR2(32)  DEFAULT 'PENDING',  -- PENDING / CONFIRMED / DISMISSED
    created_at       TIMESTAMP
);

-- Agent 任务表
CREATE TABLE IF NOT EXISTS agent_task (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type    VARCHAR2(64),
    org_code     VARCHAR2(64),
    status       VARCHAR2(32),
    input_data   CLOB,
    output_data  CLOB,
    error_msg    CLOB,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP
);

-- Agent 子任务表
CREATE TABLE IF NOT EXISTS agent_sub_task (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id      NUMBER,
    step_name    VARCHAR2(128),
    status       VARCHAR2(32),
    input_data   CLOB,
    output_data  CLOB,
    error_msg    CLOB,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP
);

-- 常用索引
CREATE INDEX idx_procurement_bid_project  ON procurement_bid(bid_project_id);
CREATE INDEX idx_procurement_bid_supplier ON procurement_bid(supplier_id);
CREATE INDEX idx_procurement_proj_org     ON procurement_project(org_code);
CREATE INDEX idx_supplier_info_id         ON supplier_info(supplier_id);
CREATE INDEX idx_payment_record_org       ON payment_record(org_code, payment_date);
CREATE INDEX idx_clue_result_org          ON clue_result(org_code, status);
